
###

GET http://45.32.158.13/api/health
Internal-Auth: -

###

GET http://45.32.158.13/api
Internal-Auth: -
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{

}


###

POST http://45.32.158.13/api/auth/authenticate
Internal-Auth: -
Accept: application/json
Content-Type: application/json

{
  "email": "admin@nikolav.rs",
  "password": "admin@nikolav.rs"
}

###

POST http://45.32.158.13/api/auth/logout
Internal-Auth: -
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{

}

###

GET http://45.32.158.13/api/auth/who
Internal-Auth: -
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{

}

###

GET http://45.32.158.13/api/webhooks
Internal-Auth: -
Accept: application/json
Content-Type: application/json

{

}

###

POST http://45.32.158.13/api/auth/register
Internal-Auth: -
Accept: application/json
Content-Type: application/json

{
  "email": "admin@nikolav.rs",
  "password": "admin@nikolav.rs"
}

###

